#!/usr/bin/env python3
import argparse
import json
import os

import argcomplete
from ansible.inventory.manager import InventoryManager
from ansible.parsing.dataloader import DataLoader
from ansible.vars.manager import VariableManager

if __name__ == "__main__":
    with open(os.path.expanduser("~/.saconfig.json")) as f:
        config = json.load(f)
    dl = DataLoader()
    im = InventoryManager(dl, [config["hosts"]])
    vm = VariableManager(dl, im)
    parser = argparse.ArgumentParser()
    parser.add_argument("host", choices=[host.name for host in im.get_hosts()])
    parser.add_argument("ssh_args", nargs="*")
    argcomplete.autocomplete(parser)
    args = parser.parse_args()
    host = im.get_host(args.host)
    ssh_host = vm.get_vars(host=host)["ansible_host"]
    os.system(f"ssh {ssh_host} {' '.join(args.ssh_args)}")
